version: "1"
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=skolsic993
      - MONGO_INITDB_ROOT_PASSWORD=Favorite93!
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=skolsic993
      - ME_CONFIG_MONGODB_ADMINPASSWORD=Favorite93!
      - ME_CONFIG_MONGODB_SERVER=mongodb
